mysticmind/reversemarkdown-net

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Blockquote.cs, src/ReverseMarkdown/Converters/Pre.cs
Try this test string:
`<pre><br/></pre>`
The `Aggregate` Linq function in the Pre Converter doesn't handle empty sequences and it throws an `InvalidOperationException`.  Fortunately (thanks [StackOverflow](http://stackoverflow.com/a/14897171)!), there's [an overload](http://msdn.microsoft.com/en-us/library/bb548744.aspx) that takes a seed, so we can pass in `string.Empty` and it won't throw that error.
Fiddle :violin: showing the difference: [https://dotnetfiddle.net/tUkhXk](https://dotnetfiddle.net/tUkhXk)
Another option would be to use `string.Join` [[MSDN](https://msdn.microsoft.com/en-us/library/57a79xd0(v=vs.110).aspx)].
=> handle empty `pre` tags without exception

src/ReverseMarkdown/Converters/Aside.cs
Hi there, 
Recently started using this project from nuget, and whilst it worked for the most part, I noticed that it did not support the `<aside>` tag.
Tested locally and I am now getting the desired results, figured I should share back upstream! (Not a lot of work, I just copied the `div` class and renamed it 😉 )
Output Before:
Output After:
=> Add support for <aside> tag

src/ReverseMarkdown/ReverseMarkdown.csproj
As title.
Original repo appears to now be compatible with .NET Core, and will stop conflicts with the namespace when using other Nuget packages that rely on HtmlAgilityPack
=> Switch to non-forked HtmlAgilityPack

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Config.cs, src/ReverseMarkdown/Converter.cs
Changed to use an enum for the unknown tags config option to make it easier to use and less complicated.
=> Use enum for the unknown tags config option

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Cleaner.cs, src/ReverseMarkdown/Config.cs, src/ReverseMarkdown/Converter.cs
I had a feature request (https://github.com/PromoFaux/Matterhook.NET/issues/14) to remove comment blocks from source, and figured it would be a good fit for this library.
Simple really, just strips `` tags from the content, see https://dotnetfiddle.net/0y1e40 for an example.
(That said, I've just looked at the section of code in my application for handling that and I'm not even using your library there! whoops.)
=> [New Feature] Optionally remove comment blocks from HTML source

README.md, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Config.cs, src/ReverseMarkdown/Converters/A.cs, src/ReverseMarkdown/Converters/Img.cs, src/ReverseMarkdown/LinkParser.cs
Gives more control over `a` and `img` tags when convert to markdown, when simplify output and when remove output.
See #27 for more info.
=> Introduce new options: HrefHandling (Smart) and WhitelistUriSchemes.

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Pre.cs
This fixes the extra line in Fenced code blocks by trimming the HTML content for linefeeds/carriage returns.
This relates to Issue #35
=> Fix extra line in Fenced Github Flavored Codeblocks

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/A.cs, src/ReverseMarkdown/Converters/Img.cs, src/ReverseMarkdown/StringUtils.cs
Fixes #38
In a markdown link `[text](href)` or imagee `![text](href)` the `text` should not contain `[` or `]` and the href should not contain `)`, `(` or ` ` (space) because these would terminate the section.
Text is also allowed to have newlines, but not multiple adjacent newlines.
This change just encodes those two fields correctly to escape these characters.
=> Escape characters which cause markdown []() links and images to break

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/H.cs
Fixes #44 
Markdown doesn't support headings inside tables, and there is no good translation, so simply remove the headings.
Text and other formatting inside the heading is still converted.
=> Prevent conversion of headings inside tables

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Ol.cs, src/ReverseMarkdown/Converters/P.cs, src/ReverseMarkdown/Converters/Text.cs
Various formatting fixes
Fixes #40 - When lists are in tables, leave as html
Fixes #41 - Preserve `&lt;` and `&gt;` in text
Fixes #42 - Fix indent of `<p>` inside `<ol>`
=> Formatting fixes for HTML which produces broken Markdown

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/P.cs, src/ReverseMarkdown/Converters/Td.cs
Fixes #48 ~~by dropping leading indentation/newline for paragraphs in tables, and replacing trailing newline with `<br>`~~. 
**Update:** Given newlines are never allowed in table cells, I decided it would be safer to just convert newline to `<br>` after the children have been converted. This way conversion logic for other elements doesn't need to have special cases for tables. One exception: I added extra check to paragraph leading newline to prevent blank line at top of table cell, similar to how p in list indent works.
Now also fixes #50.
I also realized my fix for #42 didn't take into account unordered lists (I misread `li` as `ul` 😖), so adding in the same fix for `ul` as well.
=> Paragraphs in tables

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Li.cs
Fixes #46 
Before:
>This text has ordered list.
>1. OuterItem1
>  - InnerItem1
>  - InnerItem2
>2. Item2
After:
>This text has ordered list.
>1. OuterItem1
>    - InnerItem1
>    - InnerItem2
>2. Item2
=> Increase indent spacing for nested lists to 4

src/.editorconfig, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Li.cs, src/ReverseMarkdown/Converters/Ol.cs
Fixes #54 by
- Standardizing whitespace around leading text in an `<li>` when the item also contains an inner list (for `<ol><li><ol>...` case)
- Preventing newlines around lists whose parent is an `<ol>` or `<ul>` (for `<ol><ol>...` case)
_Also adding a very basic `.editorconfig` to stop Visual Studio incorrectly formatting files with tabs. There's lots more things you could add to this config to standardize formatting and conventions if you can be bothered, but tabs v. spaces is particularly obnoxious when mixed._
=> Minor cleanup of blank lines in nested lists when html has whitespace

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Table.cs, src/ReverseMarkdown/Converters/Tr.cs
Fixed #53 by replacing `list.Aggregate` with `string.Join` which will return empty string instead of throwing if `list` is empty.
Also choosing to just drop the row if a row is empty. With the option to make first row a heading, this can cause some minor problems in the output if the first row is empty because there is no way to calculate how many columns the table has, but the conversion will proceed and the Markdown is still very readable. This doesn't seem like a case we should optimize for.
=> Don't crash when tables have empty rows

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Tr.cs
Real-world scenario when copy/pasting table from MS Word.
Issue https://github.com/mysticmind/reversemarkdown-net/issues/57
Issue introduced probably in mysticmind/reversemarkdown-net@8b535a2707b12abf20157028eea7324fd8955e4d
=> Fix handling of table with thead and td tag (instead of th).

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Cleaner.cs, src/ReverseMarkdown/Converters/Drop.cs
Excess comment removal removed closing style tag. Fix comment removal logic.
=> Fix Issue #61: Html from Outlook 2016 not being converted to Markdown

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Cleaner.cs, src/ReverseMarkdown/Converters/Div.cs, src/ReverseMarkdown/Converters/Drop.cs, src/ReverseMarkdown/Converters/P.cs, src/ReverseMarkdown/Converters/Td.cs
Additionally ignore markup whitespace (newlines) infriltrating into resulting markdown for tables.
=> Handle P and Div tags within table cell by removing leading and trailing newlines.

src/ReverseMarkdown/Converters/Tr.cs
The UseFirstRowAsHeaderRow check didn't check if first row of parent table, it checked if same as first existing tr in document. The bug occurs when there are more than one table in Html.
=> Fixed bug where Tr first row check was invalid

src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Pre.cs
- Check current node (`<pre>`)
- Check Parent node (div tag usually: Github, BitBucket, a few others)
- Check Child `<code>` node
- Check for several different language identifiers: highlight-, highlight-source, language and confluence brush:\s
- Remove explicit Confluence check and roll into the single regEx handler
This should handle support for:
* Github
```html
<div class="highlight highlight-source-json"><pre>...</pre></div>
```
* HighlightJs
```html
<pre><code class="hljs language-json">...</code></pre>
```
* BitBucket
```html
<div class="codehilite language-json"><pre>..</pre></div>
```
* Confluence ( Not really sure where this is used but just migrated the existing functionality)
```html
<pre class=""brush: python;"">...</pre>"
```
=> Add support for parsing additional Syntax Coloring schemes on import

src/ReverseMarkdown.Test/ConverterTests.When_FencedCodeBlocks_Shouldnt_Have_Trailing_Line.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_With_Confluence_Lang_Class_Att_And_GitHubFlavored_Config_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_With_GitHubFlavored_Config_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_With_Github_Site_DIV_Parent_And_GitHubFlavored_Config_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_With_HighlightJs_Lang_Class_Att_And_GitHubFlavored_Config_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_With_Lang_Highlight_Class_Att_And_GitHubFlavored_Config_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown.Test/ConverterTests.When_PRE_Without_Lang_Marker_Class_Att_And_GitHubFlavored_Config_With_DefaultCodeBlockLanguage_ThenConvertToGFM_PRE.verified.md, src/ReverseMarkdown/Converters/Pre.cs
ReverseMarkdown adds two blank lines after a fenced code block (but only one blank line after an indented code block).
The two blank lines after a fenced code block violate the following [markdownlint](https://github.com/DavidAnson/markdownlint) rule:
> [MD012 - Multiple consecutive blank lines](https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md012---multiple-consecutive-blank-lines)
>
> This rule is triggered when there are multiple consecutive blank lines in the document:
>
>     Some text here
>     
>     
>     Some more text here
>
> To fix this, delete the offending lines:
>
>     Some text here
>     
>     Some more text here
=> Remove extra blank line after fenced code block

src/ReverseMarkdown.Test/ConverterTests.WhenListContainsMultipleParagraphs_ConvertToMarkdownAndIndentSiblings.verified.md, src/ReverseMarkdown.Test/ConverterTests.WhenListContainsParagraphsOutsideItems_ConvertToMarkdownAndIndentSiblings.verified.md, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/P.cs
List items with multiple paragraphs do not render the expected Markdown. Specifically, there needs to be a blank line before each paragraph (except the first one in a list item).
To understand why, consider the HTML for one of the existing tests in ReverseMarkdown (`WhenListContainsMultipleParagraphs_ConvertToMarkdownAndIndentSiblings`):
```HTML
<ol>
<li>
<p>Item1</p>
<p>Item2</p></li>
<li>
<p>Item3</p></li></ol>
```
Let's change the paragraph content to make it a little clearer:
```HTML
<ol>
<li>
<p>Paragraph 1</p>
<p>Paragraph 2</p></li>
<li>
<p>Paragraph 3</p></li></ol>
```
With this change, the following Markdown content is generated by ReverseMarkdown:
```Markdown
1. Paragraph 1
Paragraph 2
2. Paragraph 3
```
While the might seem okay at first, copy that into Visual Studio Code and …
=> Fix list items with multiple paragraphs

src/ReverseMarkdown.Test/ConverterTests.WhenThereIsEmptyPreTag_ThenConvertToMarkdownPre.verified.md, src/ReverseMarkdown.Test/ConverterTests.WhenThereIsEmptyPreTag_ThenConvertToMarkdownPre_GFM.verified.md, src/ReverseMarkdown.Test/ConverterTests.WhenThereIsEmptyPreTag_ThenIgnorePre.verified.md, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Pre.cs
The current behavior for handling empty `<pre>` elements does not reflect the equivalent HTML rendering.
Here is the HTML from the test (`WhenThereIsEmptyPreTag_ThenIgnorePre`):
```HTML
This text has pre tag content <pre><br/ ></pre>Next line of text
```
If you copy that into an HTML document and view it in a browser, it looks something like this:
However, if you take the Markdown currently generated by ReverseMarkdown, you get something that looks like this:
This change replaces the expected Markdown in this scenario with a line of 4 spaces (or, more accurately, the number of spaces corresponding to the indentation level for the `<pre>` element -- when the element resides in a list).
```Markdown
This text has pre tag content 
Next line of text
```
> **Note:**
>
> I will be the first to …
=> Correct empty <pre> behavior

README.source.md, src/ReverseMarkdown.Test/ConverterTests.When_SuppressNewlineFlag_PrefixDiv_Should_Be_Empty.md, src/ReverseMarkdown.Test/ConverterTests.When_SuppressNewlineFlag_PrefixDiv_Should_Be_Empty.verified.md, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Config.cs, src/ReverseMarkdown/Converters/Div.cs
In some cases there is HTML that will wrap standard text in `div` tags like this
```
<div>hello</div><div>world</div>
```
The default behavior for the ReverseMarkdown library is to append two newlines for each item, a prefix and suffix `\r\n` per `div` tag, resulting in something that looks like this:
```
hello
world
```
In this PR, I propose adding a new `Config` option called `SuppressNewlines` that will remove the prefixed newline from `div` tags not enclosed in `td` tags, such that the output may look like the following:
```
hello
world
```
would it be okay if the dotnet framework 4.7.2 builds were re-enabled? my product doesn't currently support dotnet core :(
=> adds newline suppression for divs

src/ReverseMarkdown.Test/ChildConverterTests.cs, src/ReverseMarkdown.Test/Children/IgnoreAWhenHasClass.cs, src/ReverseMarkdown/Converter.cs
+ Added additional constructor with parameter (`param Assembly[] additionalAssemblies`) to the `Converter` constructor with support for custom converters and converters that inherit from existing converters.
+ Changed all `private readonly` fields in `Converter` to `protected readonly`
+ Changed all `public` methods in `Converter` to `public virtual`
+ Added test class/case for testing the constructor.
Closes #384
=> [Draft] Converter Inheritance Support

README.md, README.source.md, src/ReverseMarkdown.Test/ConverterTests.WhenThereIsInputListWithGithubFlavoredDisabled_ThenConvertToTypicalMarkdownList.verified.md, src/ReverseMarkdown.Test/ConverterTests.WhenThereIsInputListWithGithubFlavoredEnabled_ThenConvertToMarkdownCheckList.verified.md, src/ReverseMarkdown.Test/ConverterTests.cs, src/ReverseMarkdown/Converters/Li.cs
This resolves issue #404 (Add support for "Github Flavored Markdown Task Lists")
Example:
**HTML:**
```html
<ul>
<li><input type="checkbox" checked> Complete the project report</li>
<li><input type="checkbox"> Submit the report</li>
<li>This is a regular list item</li>
</ul>
```
**Converted Markdown:**
```md
- This is a regular list item
```
Markdown Preview:
- This is a regular list item
=> Add support for "Github Flavored Markdown Task Lists"
